"""empty message

Revision ID: c7f2572271b3
Revises: 6665526a5d62
Create Date: 2021-12-16 13:14:02.378204

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c7f2572271b3'
down_revision = '6665526a5d62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friends', 'created_at')
    op.drop_column('friends', 'updated_at')
    op.drop_column('friends', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('friends', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('friends', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
