"""empty message

Revision ID: be2d24acc88d
Revises: ce1fd984079e
Create Date: 2021-12-29 11:55:00.958666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be2d24acc88d'
down_revision = 'ce1fd984079e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('routes', sa.Column('activity_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'routes', 'activities', ['activity_id'], ['id'])
    op.drop_column('routes', 'activity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('activity', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.drop_column('routes', 'activity_id')
    op.drop_table('activities')
    # ### end Alembic commands ###
