"""empty message

Revision ID: 6665526a5d62
Revises: f604d62b5a1c
Create Date: 2021-12-15 14:51:37.924723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6665526a5d62'
down_revision = 'f604d62b5a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('friends', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('friends', 'friend_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('friends', 'friend_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('friends', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
